name: pexels
version: 0.1.1
description: Unofficial wrapper of Pexels REST API for the Dart Language.
author: Kennedy Tochukwu Ekeoha <ekeohak@gmail.com>
repository: https://github.com/xenoken/pexels
homepage: https://github.com/xenoken/pexels
environment:
  sdk: '>=2.1.0 <3.0.0'
dev_dependencies:
  test : '>=1.0.0'
